### ISSUE TITLE
[DRIVER] Add an option to pre-load specified kernel module (specified by path to .ko file) before starting Hyperion-NG main daemon

### ISSUE THREAD

**Issue by S-trace** [webosbrew/hyperion.ng-webos-loader#18]
Hi.

I have a TV which require to load ch341.ko to let wired LED controller to work on my TV.
Now I need to manually load the ch341.ko via SSH and then manually restart HyperHDR to make it work.

Is it possible to add an option to insmod the specified .ko module before starting Hyperion-NG main  process?

Thanks.

**Comment by throwaway96** [comment]
You can put a script in `/var/lib/webosbrew/init.d` to load the module.

**Comment by throwaway96** [comment]
I have no plans to do this currently, and I doubt anyone else does. If you can come up with a compelling idea for how such a feature would work, I may reconsider.
